#!/usr/bin/env groovy
// This will donwload the common Jenkins Job
// To modify the Job, update the MCD MCDroject.groovy
// DO NOT EDIT THIS FILE
@Library('CommonLib@master') _
def common = new com.mcd.CommonDeployPipeline()
common.runPipeline()

